---

CommonName: Totally Legit CA Inc.
OrgName: Totally Legit CA Inc.
OrgUnitName: Certificate Authority
Email: sup@legit-ca.org

URL: legit-ca.org
IAI: https://legit-ca.org/crt/
CSR: https://legit-ca.org/csr/

