---

Dir: ./work

CommonName: Totally Legit CA Inc.
OrgName: Totally Legit CA Inc.
OrgUnitName: Certificate Authority
Email: sup@legit-ca.org

URL: legit-ca.org
AIA: https://legit-ca.org/crt/
CRL: https://legit-ca.org/crl/

Digest: sha512
